### ISSUE TITLE
Wrong URL for reports on Front Dashboard

### ISSUE THREAD

**Issue by pagenoare** [AppEnlight/main#41]
Yo,

The URL for "Exceptions" box is wrong. It's `https://appenlight.com/browser#/reports?app=1&start_date=2015-03-17T17:58` which redirects me to front dashboard. However, the top menu icon for "Error reports" is pointing to `https://appenlight.com/browser#/report?app=1&start_date=2015-03-17T17:58`

I'm talking about this one box (Front Dashboard):
![](http://i.codethis.net/2015/03/4577c8414dc35eb79701ae9ae1a95794.png)

Regards,
Kacper.

**Comment by ergo** [comment]
fixed, thanks

**Comment by pagenoare** [comment]
yup, works. thanks.

2015-03-18 15:43 GMT+01:00 Marcin Lulek <notifications@github.com>:

> fixed, thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppEnlight/main/issues/41#issuecomment-83002063>.
>



-- 
Kacper Krupa.
