### ISSUE TITLE
Error details - broken tabs after page refresh

### ISSUE THREAD

**Issue by pagenoare** [AppEnlight/main#42]
So, when u enter some error details, and swap tab to for example "Request details", and hit F5, you're getting something like:

![](http://i.codethis.net/2015/05/9aa139be41996fc9cf7ec8c6d8b49f47.png)

When i switch tab again, the correct data appears.
Currently noticed for tabs "Request details" and "Request logs" (loading icon stays forever).

**Comment by ergo** [comment]
fixed :-)
